name: ci
on:
  workflow_dispatch:
  push:
    branches: [main]

concurrency:
  group: environment-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Accurate0/rust-toolchain@main
        with:
          toolchain: stable
          override: true

      - name: cargo build
        run: cargo build --release

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Accurate0/rust-toolchain@main
        with:
          toolchain: stable
          override: true

      - uses: katyo/publish-crates@v1
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          check-repo: ${{ github.event_name == 'push' }}
          ignore-unpublished-changes: true
